### ISSUE TITLE
Upgrade from Roman Sky repo... can I just install over the top?

### ISSUE THREAD

**Issue by pperrin** [fluffy-critter/Feed-on-Feeds#2]
I upgraded from the old original .5 version to the current (2 year old?) romansixty version - can yours just be installed over the top?

**Comment by fluffy-critter** [comment]
Yes, but you'll need to run install.php again. Also instead of installing from an archive I recommend just doing a `git clone` since then you can just switch forks by changing which branch you're on or whatever. It'd also make it easier for you to switch to your own fork so that you can make pull requests for any changes you want to submit. :)

Also the default config file has changed significantly. You'll want to make sure that you've updated everything, especially since sometimes the failure messages can be a bit inscrutable if something's misconfigured.
