### ISSUE TITLE
plugin preference are ignored in 'shared' view.

### ISSUE THREAD

**Issue by pperrin** [fluffy-critter/Feed-on-Feeds#4]
I disabled item targets as its not compatible with my version of PHP, but the plugin was still called when viewing shared items.

I think this is because preferences are user based, and the 'shared' page could be accessed by anyone.

Maybe better to delete incompatible plugins...

**Comment by fluffy-critter** [comment]
Plugins are called at item fetch time, not at render time, so unfortunately those errors are going to stick around in the old items. I don't think there's an easy way to force FoF to re-fetch an item's content either, unfortunately. 

##

**Comment by pperrin** [comment]
The ones I had problems with are 'render filters' which get called at render time. I haven't dug in to any others yet. I have cobbled the ones I had trouble to make them backwardly compatible (but clunkier!).

**Comment by fluffy-critter** [comment]
The only render filter is the on-demand image loader. I probably forgot to plumb through something for those preferences. 

There are many good reasons to upgrade to PHP 5.5, incidentally. :)

##

**Comment by pperrin** [comment]
Oops - my mistake the other one was an 'add item filter' - changes 'a' to target blank (should probably be a render filter?).

It was that and the on-demand that caused problems - but couldn't swear to which one crashed the shared view - (writeHTML with a node parameter).

My current host only does upto 5.5.1... the html thing need 5.5.3 I believe.

I have been meaning to move hosting for years, but have so many domains, sites, redirects etc that I'd have to reconfigure and redirect when my IP changes I have put it off...

**Comment by fluffy-critter** [comment]
Render filters are very new - I only added them a couple days ago. :) I haven't had a chance to turn item_target into one yet.

The docs say that the saveHTML($node) thing was added in php5.3.6, as you had mentioned in some other bug report. So as long as you're running the latest 5.3 you should be fine. But 5.4 is a lot better, and 5.5 adds even more stuff that I'm starting to use in my projects. It's a good idea to upgrade. Your current web host should be able to do the upgrade for you. If not then they aren't a web host worth staying with.

Personally I like dreamhost for PHP apps. (They kind of suck for Python, though, and Java and node apps require a VPS which can get expensive.) Currently I run FoF on a LiNode instance but that's not for the faint of heart. 

##

**Comment by pperrin** [comment]
Oh! being pretty actively being developed then!

I am on a legacy hosting solution - sold on about 4 times since I took it out(!) - but always had 'more important' things to spend my time on (though it is very expensive). I have admin access on my VS but not root so cant actually install a more recent PHP - and they wont (I think they want to shut it down really).

I am looking at google app engine right now.

**Comment by fluffy-critter** [comment]
App Engine is probably a fine choice, although I've never tested FoF on it. Also it looks like their MySQL offering is still on the expensive side, and I don't know if their storage model is compatible with SQLite (which is what I mostly work with these days because it's a lot easier to deal with and performs well enough for a single-user application).

**Comment by fluffy-critter** [comment]
Okay, in any case, I just converted item_targets to a render filter, so future fetched items should be fine as long as you have the plugin disabled. Render filters also don't apply to the shared items view (since render filters are for things that are for the reader's benefit) and I haven't investigated how hard that'd be to change (since I don't think the user preferences are available on the shared view). But this change does make it so that the shared feed doesn't get crapified with `target="_blank"` links (which bugs the hell out of me).

**Comment by pperrin** [comment]
I am quite a jquery fan - have you thought about client side UI stuff? I see it uses prototype (wich I used once several years ago!) -- mabye a wiki would be useful? Or exchange emails?

**Comment by pperrin** [comment]
Oops - the image thing is putting <p> around the text before the enclosure - so the 'show enclosure' can't find the hidden div cos its not a sibling.

**Comment by fluffy-critter** [comment]
The FoF codebase is a bit of a mess right now because of all the different people doing short-term hacks on it (and the original version was pretty much a short-term hack anyway). A lot of the plugins can probably just go away, anyway, because DOMDocument should theoretically automatically fix a lot of the problems that it tries to fix in the first place. They should definitely be refactored in any case.

The client-side UI JavaScript is especially bad at this point. Someone should probably rewrite it all to just be ECMAScript 5 or 6 or whatever. I don't see any reason to pull in jQuery, either.

**Comment by fluffy-critter** [comment]
Wow, this conversation thread really got away from its core issue.

Let's see. Plugin refactoring has its own issue #5 (which @RomanSixty has also already done a bunch of work on although I feel like it could still be better).

The core issue being reported has been fixed by a combination of things (moving a bunch of item filters into render filters, not aggressively or uselessly caching item content, etc.).

The other issues raised in this conversation probably should get their own tickets, so if someone cares to, they can certainly reopen them in their own things. :)
